source 'https://rubygems.org'

gem 'rake'
gem 'therubyracer', git: 'git@github.com:cowboyd/therubyracer.git', branch: :master
gem 'awesome_print'
gem 'pry'
gem 'sanitize'
gem 'minitest'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'sinatra-activerecord'
gem 'sinatra-strong-params', require: 'sinatra/strong-params'
gem 'sinatra-flash'
gem 'sass'
gem 'hamlit'
gem 'html2haml'
gem 'i18n'
gem 'rack-contrib'
gem 'rack-cache'
gem 'nokogiri'
gem 'uglifier'
gem 'jsmin'
gem 'sprockets'
gem 'sqlite3'
gem 'bcrypt'
gem 'coffee-script'
gem 'json' # required by TinyMCE uploadfile plugin
