source 'https://rubygems.org'

gem 'kramdown', git: 'git@github.com:sixtyfive/kramdown.git', branch: :asciitable
gem 'awesome_print'
gem 'pandoc-ruby'
gem 'pry'
gem 'sanitize'
gem 'rubocop'
gem 'minitest'
gem 'sinatra'
gem 'thin'
gem 'sass', '>=3.3.0'
gem 'haml'
gem 'html2haml'
gem 'i18n'
gem 'rack-contrib'
gem 'rerun'
gem 'bourbon'
gem 'neat'
gem 'normalize-scss'
gem 'nokogiri', '=1.6.8.1'
gem 'publishr'
gem 'rubyzip', '< 1.0.0' # to be compatible with docx_converter
gem 'docx_converter' #, git: 'git@github.com:michaelfranzl/docx_converter.git'
gem 'guard'
gem 'uglifier'
gem 'sprockets'
