#!/usr/bin/env ruby

unless ARGV.length == 3
  puts "Usage: script/compile <locale> <cefr_level> <chapter_name>"
  exit
end

require 'pathname'

ROOT = Pathname(__FILE__).dirname.parent
require_relative (ROOT + 'config.rb').expand_path
require_relative (ROOT + 'lib' + 'textbookr.rb').expand_path

Textbookr::Chapter.convert(locale: ARGV[0], cefr_level: ARGV[1], chapter_name: ARGV[2])
